### PR TITLE
Adding an explicit glyph->load method, and documentation

### PR DESCRIPTION
**Pull request by HinTak**
There are very few reasons to use this as it is called implicitly if
needed, by most of the other methods.

A few of these reasons include: timing or profiling tests of
FreeType, debugging FreeType via side effects of glyph loading
(by setting FT2_DEBUG).

### CODE REVIEW

**Comment by HinTak** [comment]
I thought of calling $glyph->width() and just throw away the result, but this is probably better. Not sure if you would like this added though.

**Comment by basiliscos** [comment]
Please, add some test :)

**Comment by HinTak** [comment]
Not sure how to test this - load() alone (vs width() for example) is only useful for option that involves side effects, such as timing, profiling, or debugging FreeType (with FT2_DEBUG) . I suppose one can ask that the time of various load flags to be in the right order e.g loading bitmap + outline is larger than either alone but smaller than the sum?

But that to some extent depend on how fast your computer is...

I'll think of something.

**Comment by HinTak** [comment]
Hmm, it looks like I might be digging a hole for myself. I think I want to add the $face->load_flags getter/setter routines also, to allow load_flags to be modified after the constructor. In FreeType, they are per load_glyph, but since Font::FreeType keeps it as a face extra, it needs to be a face property, although it is really a glyph one.

Or should the value be automatically copied from one to the other, and in what direction?

This also gives a test on the earlier compute_metrics flag too - with it is supposed to be slower.

**Comment by basiliscos** [comment]
I think we'd need to have the per-glyph payload (extra), i.e. in glyph constructos 

```perl 

my $glyph = $face->glyph_from_char('A', FLAGS = 0 );
my $glyph = $face->glyph_from_char_code(65, FLAGS = ...);

```

and then 

```c

... flags = font_extra->glyph_load_flags | glyph_extra->glyph_load_flags;
errchk(FT_Load_Glyph(face, glyph->index, flags),  "loading freetype glyph");

```

**Comment by HinTak** [comment]
I don't think newly setted flags should be or'ed with existing - that's too surprising for users. What I mean is it should be set fresh. If the user wants to or existing flags, he/she should do it on the client side. So a getter routine is still needed. But it looks like you want it as a glyph method rather than a face method.

This is perhaps a bit confusing as the flags is shared between all glyph and persistent to the next glyph, if it is available as a glyph method.

Actually at the moment the flags is already shared and persistent across glyphs if modified...

**Comment by HinTak** [comment]
Actually I think face->load_flag should be persistent, but the glyph methods should not affect other glyphs. Unfortunately load is not invoked where glyph_from_* is issued, so it would be too surprising as a glyph method argument as it affects other glyphs.

**Comment by HinTak** [comment]
I have added the face->load_flags methods. I don't think it can/should be done per glyph as it is fairly painful setting it and restoring it per glyph, especially given that the flags is not used unless/until any operation that requires load_glyph . Thus it would be too confusing, if one does something like this:

```
my $glyph1 = $face->glyph_from_index(x, flag1);
# not playing with $glyph1 yet
my $glyph2 = $face->glyph_from_index(y, flag2);

#now go back to glyph1...
print $glyph1->width;
# this gives value of glyph1 under flag2, as load_glyph only happens
# when we try to get non-trivial properties
```

**Comment by HinTak** [comment]
I think this is as far as I can do a basic test on glyph->load also.

**Comment by HinTak** [comment]
There are two more changes which I wonder if you are willing to take, on my font-diag branch. They are:

https://github.com/HinTak/p5-Font-FreeType/commit/dca5387508b07d84e2682304d5aca1771b3018a9
'is_outline() should default to false if anything goes wrong? '
https://github.com/HinTak/p5-Font-FreeType/commit/e88010d950688c21d30273de3263a70a0ab2a604
'we want the loaded_glyph_idx to be correct when FT_Load_Glyph is called'

My font-diag branch and the script
https://github.com/HinTak/p5-Font-FreeType/blob/font-diag/examples/font-diag.pl
illustrates what I am trying to do, with the enhanced FreeType backend of FontVal (it has a few extra things). 

Binaries are at, whatever you fancy:
https://github.com/HinTak/Font-Validator/tree/master/bin/fedora-fc28-x64
https://github.com/HinTak/Font-Validator/tree/master/bin/ubuntu-16.04-x64
https://github.com/HinTak/Font-Validator/tree/master/bin/Darwin
https://github.com/HinTak/Font-Validator/tree/master/bin/Win32
https://github.com/HinTak/Font-Validator/tree/master/bin/Win64

running the script should give you something like this, which is the equivalent of the C#/python infos provided by the other bindings:
```
perl ... font-diag.pl ../t/data/Vera.ttf
_rast_W_FT_VALUE_OUT_OF_RANGE_SLOOP_ZERO SLOOP: Glyph ID 241, At ByteOffset 67
_rast_W_FT_VALUE_OUT_OF_RANGE_SLOOP_ZERO SLOOP: Glyph ID 244, At ByteOffset 67
```

This is why I need the $glyph->load method, and also the small re-ordering of code in
https://github.com/HinTak/p5-Font-FreeType/commit/e88010d950688c21d30273de3263a70a0ab2a604
'we want the loaded_glyph_idx to be correct when FT_Load_Glyph is called'
.

I am okay if you don't like either of the two changes. If you are okay with either of them or both, I can add them to this stack.

**Comment by basiliscos** [comment]
I'm fine with your changes, but let's do that gradually. 

1. What is ".notdef" ? It looks as separate feature. Please add doc to FreeType + update docs + tests (+ font?), i.e. good PR (not just point to commit, please)  - most likely I'll merge it.

2. The moving `extra->loaded_glyph_idx = glyph->index;` worth also separate PR. again, it needs tests, explaination, use cases, breakage analysis   - most likely I'll merge it. (+ may be add `slot_valid`, may be not, should be discussed). 

3, Do not throw in `ensure_outline_loaded` might be the most problematic one. I'd like to keep **the perl** interface throwing, although this one does not needs to be throwing; this is implementation. I'm willing more to have separate method. However, if you can provide code + font where the current interface crashes (SEGFAULT), and your approach will be able to deal with that - that's will be strong enough reason for breaking changes.

PS. There is a convention that `ensure_*` methods usually throw exception if a condition is not met. So, if it will be changed to return `false`, then it have to be renamed too.

**Comment by basiliscos** [comment]
PS. Please, feel free to poke me more on weekends, as I might be too busy/forget if there something expected me to do on weekdays.

**Comment by basiliscos** [comment]
4. `load` is also worth a separate PR. It should be somehow better named, like `load_iterate` or something like that, also it should set `$_[0]` rather then `$_`. Other then that minors, looks fine for me, most likely will be merged.

**Comment by HinTak** [comment]
I have resolved the conflict (have the changes in chronological order) - but I suspect you may prefer merge order (even if older-date entries appear futher up)?

**Comment by basiliscos** [comment]
Looks good for me now, I'll merge and release on the this week (probably on the weekends)

**Comment by HinTak** [comment]
Thanks!

**Comment by basiliscos** [comment]
You're welcome. It just has been uploaded to cpan as 0.14 https://metacpan.org/recent

**Pull request merged**
